entries/unwrap.xml
PR for the v3 branch. Adds a `.unwrap(selector)` signature. Fixes https://github.com/jquery/api.jquery.com/issues/689.
Ref https://github.com/jquery/jquery/commit/7b09235ceed57bbcc26fc2c76147eb4e95ebdb92
=> unwrap: add `selector` argument

entries/jQuery.htmlPrefilter.xml
/cc @gibson042 @kswedberg @AurelioDeRosa 
- Would be grateful for a speedy review. Thanks!
Fixes gh-727
=> jQuery.htmlPrefilter: add new entry

entries/jQuery.parseJSON.xml
The deprecation note has been moved to the top of the description as it's the
most important information about the API. This is also how other pages for
deprecated APIs are documented.
Also, the message has been rephrased a little as JSON is a string, not an
object.
Ref #899
=> jQuery.parseJSON: Move the deprecation note to the top, rephrase it

entries/jQuery.when.xml, pages/Types.html
Technically replacing Deferred with Thenable would work, but mentioning Deferred and Promise directly should make this easier to understand for new and existing users.
Fixes #906.
=> jQuery.when: Add Thenable and Promise as acceptable types

entries/selector.xml
Follows-up e3c9d15239, which added it to the wrong category.
=> Selector: Move from global to instance property category

entries/jQuery.holdReady.xml, entries/jQuery.ready.xml
Also:
- Categorise `jQuery.holdReady` in events/document-loading,
to match `ready()` and `jQuery.ready.promise()`.
- Categorise `jQuery.holdReady` in properties/global-jquery-object-properties,
to match `jQuery.fx.off()` and `jQuery.ready.promise()`.
Fixes #205
=> Document jQuery.ready

entries/outerHeight.xml, entries/outerWidth.xml
=> outerHeight(): Specified type of passed arguments to callback

entries/one.xml
I only found the `data` after inspecting `event` further. This change will make it clearer where to get `data` (and consistent with the docs for `.one( events [, selector ] [, data ], handler )` and `.one( events [, selector ] [, data ] )`).
If people think it would be great to make this change for other jquery fns too, the following fns still use the old desc:
```
entries/bind.xml
entries/blur.xml
entries/change.xml
entries/click.xml
entries/contextmenu.xml
entries/dblclick.xml
entries/delegate.xml
entries/error.xml
entries/focus.xml
entries/focusin.xml
entries/focusout.xml
entries/keydown.xml
entries/keypress.xml
entries/keyup.xml
entries/live.xml
entries/load-event.xml
entries/mousedown.xml
entries/mouseenter.xml
entries/mouseleave.xml
entries/mousemove.xml
entries/mouseout.xml …
```
=> Indicate where data will be passed in $.one doc

entries/offset.xml, entries/position.xml
Ref https://github.com/jquery/jquery/pull/3487
=> Offset: Be more precise about the origins for .offset() and .position()

entries/closest.xml
While reading the docs I noticed highlight was spelled "hilight" and corrected the spelling.
=> Correct spelling of "highlight"

entries/callbacks.fireWith.xml, entries/event.stopImmediatePropagation.xml, entries/event.stopPropagation.xml, entries/jQuery.ajaxSetup.xml, entries/jQuery.globalEval.xml
Following #1066, I have found several functions without a return type. I have assigned appropriate types to these. I have additionally figured out the signature of callbacks.callWith, and fixed that as well. The documentation had a mistake in it, it stated that if the argument is not an array, the callbacks will receive a single argument, but this is not true, it is in fact passed as the second argument of apply.
Finally, I have not assigned a return type to jQuery.error, as it never returns therefore has no return type.
I agree to the CLA. Do I need any paperwork? EDIT: Figured it out.
=> Fix signatures of multiple functions

entries/jQuery.ajax.xml
I think the capitalization made dataType being a property name a bit unclear.
=> Make a minor correction

entries/load.xml
Solves issue #1125 
Behavior determined by Dave Methvin
=> Fix singular references to matched elements

entries/jQuery.globalEval.xml
=> jQuery.globalEval: Document the nonce option

entries/jQuery.xml
…when passing `null/undefined/[]/""` to `jQuery()`  
See https://github.com/jquery/api.jquery.com/issues/1136
=> "Returning an Empty Set" clarifications

pages/Types.html
From `as passed` to  <code>is passed</code> as in:
When a string as passed as an argument
=> a tiny fix: {a,i}s passed as

entries/andSelf.xml, entries/context.xml, entries/deferred.isRejected.xml, entries/deferred.isResolved.xml, entries/die.xml, entries/error.xml, entries/jQuery.boxModel.xml, entries/jQuery.browser.xml, entries/jQuery.sub.xml, entries/live.xml, entries/load-event.xml, entries/selector.xml, entries/size.xml, entries/unload.xml, entries2html.xsl
The upgrade is necessary to be able to write examples for newer APIs.
Examples for removed APIs have been removed as they'd no longer work.
Fixes gh-982
=> All: Upgrade jQuery used in examples from 1.10.2 to 3.4.1, remove deprecated examples

entries/jQuery.ajax.xml
=> Clarify that errorThrown and statusText will be empty strings in HTTP/2

entries/jQuery.post.xml
Fixed the description for jQuery.,Post()
=> jQuery.post: Indicate POST is mainly for sending data, not receiving it

entries/jQuery.globalEval.xml, entries/jQuery.xml, pages/Types.html
Since jQuery 3.5.0, `jQuery.globalEval` accepts an optional third parameter
accepting a document in which context the code will be evaluated.
This commit also adds the Document type and links it to one of the jQuery
signatures; so far it was using `type="document"` which linked to a non-existent
types section.
Ref jquery/jquery#4601
=> jQuery.globalEval: Document the document parameter

entries/jQuery.extend.xml
This is done to reduce the confusion as the single-argument signature behaves
completely differently than the other one.
Ref jquery/jquery#4748
Fixes gh-1164
=> jQuery.extend: Separate the one-argument signature from the multiple-arguments one

entries/jQuery.get.xml
Added a `.get()` example to show how to request a different page from the same domain.
Noticed all the examples on this page were for appending to the current url rather than changing the url to another page on the same domain. May be helpful to have here.
=> jQuery.get: Add an example using a root-relative path

entries/jQuery.trim.xml
=> jQuery.trim: Describe differences between String#trim & jQuery.trim

entries/addClass.xml, entries/removeClass.xml, entries/toggleClass.xml
[From jQuery 3.3.0](https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/), if using a function as a argument for `.addClass`, `.removeClass` and `.toggleClass`, the function is allowed to return a `Array`. However, this is not reflected in the return types.
=> addClass:removeClass:toggleClass: Update function signatures

entries/prop.xml, entries/removeProp.xml
Ref https://github.com/jquery/jquery/issues/4887
=> removeProp and prop: clarify recommendations regarding native properties

entries/removeClass.xml
That signature removes all classes which wasn't that clear from the original
signatures until one read the description.
I recommend reviewing with whitespace changes disabled as the whole file had to be indented.
This has been a point of confusion at my company recently and even I didn't quickly find that it was actually documented as the `removeClass( [ className ] )` signature was describing two essentially different signatures.
=> removeClass: Separate the signature with no parameters

entries/jQuery.getScript.xml
When executing a callback provided to the optional `success` parameter of [`$.getScript()`](https://api.jquery.com/jquery.getscript/),
we can assume the script has been executed already.
Just like when using `.done()` on the returned jqXHR object.
See issue #1207.
=> jQuery.getScript: Script has been executed before the `success` callback

entries/prevAll.xml
`.prevAll()` returns elements in the reverse document order. This can pose issues when used with APIs like `.append()` or `.wrapAll()`. Document how to deal with the issue with help from `jQuery.uniqueSort()`.
Ref jquery/jquery#5149
Screenshots of the `.prevAll()` page additions from this PR:
1. A note added at the end of the main description (just before examples): <img width="746" alt="Screen Shot 2022-12-19 at 15 14 34" src="https://user-images.githubusercontent.com/1758366/208445623-43524580-6740-4dca-8557-322c937069f5.png">
2. A new example at the end of the page: <img width="765" alt="Screen Shot 2022-12-19 at 15 14 56" src="https://user-images.githubusercontent.com/1758366/208445660-a9b70119-4e34-4679-9280-d1d67bb125a3.png"> <img width="782" alt="Screen Shot 2022-12-19 at 15 15 08" …
=> prevAll: Document issues with reverse doc order

entries/jQuery.map.xml, entries/jQuery.uniqueSort.xml
_1\. `jQuery.map`: Accept array-like input_
_2\. `jQuery.uniqueSort`: Accept array-like input, fix typos_
Apart from array-like inputs being officially allowed in
`jQuery.uniqueSort` now, in a few places in examples
it used to be referred to as `unique` instead of `uniqueSort`.
----- 
The second one is particularly interesting. For some reason, there's even an example directly claiming `jQuery.uniqueSort` doesn't work on array-likes when its code says something completely opposite - especially that it's sometimes used on jQuery collections. [We even test it on an "Arrayish" class](https://github.com/jquery/jquery/blob/024d87195ac46690023e2b0b308d4406a8a5a27e/test/unit/selector.js#L1957-L1962)!
=> jQuery.map:jQuery.uniqueSort: Accept array-like input, fix typos

entries/bind.xml, entries/data.xml, entries/delay.xml, entries/delegate.xml, entries/dequeue.xml, entries/detach.xml, entries/each.xml, entries/hide.xml, entries/jQuery.dequeue.xml, entries/live.xml, entries/nth-child-selector.xml, entries/nth-last-child-selector.xml, entries/nth-last-of-type-selector.xml, entries/prev.xml, entries/remove.xml, entries/removeAttr.xml, entries/replaceWith.xml, entries/show.xml, entries/slideToggle.xml, entries/slideUp.xml, entries/toggle.xml, entries/unwrap.xml, entries/val.xml, entries/visible-selector.xml
fixes #1226 
The same issue was replicated across 24 files, which this PR covers.
=> All: Fix button selectors

categories.xml, entries/add.xml, entries/after.xml, entries/before.xml, entries/jQuery.ajax.xml, entries/jQuery.support.xml
jQuery 1.10/2.0 & 1.11/2.1 now have dedicated version categories; the same applies to 3.6. A few other version descriptions have been tweaked.
The `.add( selection )` signature is now documented to have arrived in 1.1 instead of 1.3.2. Tests for this behavior got added in https://github.com/jquery/jquery/commit/a5f9108a2109b2ed5778af860b0928d8e6b0fdd2.
A cetegory in one of `before` & `after` signatures was updated from `1.10` to `1.10-and-2.0`, fixing a broken category link.
This should fix the `spider-check` that is broken right now on GitHub Actions: https://github.com/jquery/api.jquery.com/actions/runs/4789051019/jobs/8516452787
=> All: Add missing jQuery versions to categories, update entries

categories.xml, entries/prevAll.xml, entries/uniqueSort.xml, entries2html.xsl
`.prevAll()` returns elements in the reverse document order. This
can pose issues when used with APIs like `.append()` or `.wrapAll()`.
Document how to deal with the issue with help from `jQuery.uniqueSort()`.
Ref gh-1215
Ref jquery/jquery#5149
This is another version of #1215, meant to be merged after jQuery 3.7.0 gets released.
This PR includes a stub for the `3.7` category and changes the jQuery version used in examples to the `3.x-git` one. This needs to be changed to the real `3.7.0` one after that version gets released. Those two issues need to be addressed before this PR is moved out of the draft status. However, other than that, the PR is ready for reviews.
Screenshots of the `.prevAll()` page changes from this PR: 
1. A note at the end of the main description (just before …
=> prevAll:uniqueAll: Add uniqueAll, use it in reverse doc order examples

.github/configs/hydra-config.json, .github/workflows/spider-check.yaml
Twitter pages now do 302-redirects to themselves for users without a specific cookie set which trips the crawler; avoid checking Twitter links by abusing the `exclude_scheme_prefixes` option of the crawler.
Since the project only accepts options in a form of a configuration file, we also need to clone the API repo to provide such a file.
=> Build: Skip checking Twitter links in the hydra crawler

.mailmap
An old tag used a previous email.
=> Build: add timmy emails to mailmap

.github/dependabot.yml, .github/workflows/node.js.yml, .github/workflows/spider-check.yaml, .github/workflows/typesense.yaml
Also, set up automatic Dependabot updates of actions grouped into a single PR as Core does.
Ref jquery/jquery#5503
=> Build: Refer to commits of GitHub Actions, upgrade them

categories.xml
- also made formatting consistent for all deprecated/version categories
The styling for the warning messages is in the [companion PR in jquery-wp-content](https://github.com/jquery/jquery-wp-content/pull/468) (some of the styling already existed). I prefer to set these explicitly rather than try to generate them programmatically. And, this gives us a little side advantage of being able to modify the message for specific categories, if needed. I made use of that when there were multiple versions and pluralized the message.
Ref https://github.com/jquery/jquery-wp-content/pull/468
Ref https://github.com/jquery/jquery-wp-content/issues/462
=> Categories: add version support warnings to old versions

categories.xml
I added a `4.0` category here as well. We are close to the release and I'd prefer start merging docs changes for jQuery 4.0 instead of waiting for the release. I added a banner to the category indicating it's a pre-release, we can update it if we release an RC and/or a stable release, but the docs would remain the same.
I'll base other docs PRs for 4.0 on this PR so that the category is there. For this reason, this branch is pushed to `jquery`, not my fork - otherwise I'd be only able to submit PRs on my fork or to base them on `main`.
=> All: Add a 4.0 version category

entries/jQuery.xml
This adds an actual quick-closed tag in this code example, as it is implied by the text that there can be one:
> Tags that cannot contain elements may be quick-closed or not:
```
$( "<img>" );
$( "<input>" );
```
to
> Tags that cannot contain elements may be quick-closed or not:
```
$( "<img>" );
$( "<input />" );
```
=> jQuery: Add a self-closed tag back to an example

entries/attr.xml
Fixes gh-1243
Ref jquery/jquery#5452
Ref jquery/jquery-migrate#540
A new version of #1254.
=> Attr: Document jQuery 4 boolean attribute changes

entries/ajaxComplete-shorthand.xml, entries/ajaxError-shorthand.xml, entries/ajaxSend-shorthand.xml, entries/ajaxStart-shorthand.xml, entries/ajaxStop-shorthand.xml, entries/ajaxSuccess-shorthand.xml
jQuery 3.3.0 deprecated regular event shorthands:
https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/ The AJAX ones only got deprecated in 3.5:
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
Interstingly, the AJAX shorthands were already added to the `deprecated/deprecated-3.5` category, only the `deprecated` attribute was set incorrectly.
=> All: Mark ajax event shorthands as deprecated in 3.5, not 3.3

entries/keypress.xml
=> Fixing keypress docs renaming wrong instances of "keyup"

entries/text.xml
Changing the wording to indicate, as said by @dmethvin, that it's not supported and may not behave the same way in some future version.
Fixes #1244
=> Changing wording from "cannot" to "should not"

.github/configs/hydra-config.json, .github/workflows/spider-check.yaml
The oembed endpoint responds HTTP 429 Too Many Requests too often; perhaps because almost every page links to one.
=> Build: Skip checking oembed wp-json links in the hydra crawler

categories.xml, entries/jQuery.Deferred.exceptionHook.xml, entries/jQuery.Deferred.getErrorHook.xml, entries/jQuery.Deferred.getStackHook.xml
Also, create a page for the now deprecated `jQuery.Deferred.getStackHook`.
Fixes gh-1221
Fixes gh-1246
Page screenshots:
=> All: Create pages for `jQuery.Deferred.{getErrorHook,exceptionHook}`

.github/workflows/node.js.yml, entries/jQuery.get.xml, entries/jQuery.post.xml
In jQuery 3.x and older, when providing a `null` value for `success` you also have to provide the `data` parameter; you can set it to `undefined`.
Document this restriction of `jQuery.get` & `jQuery.post`.
Ref jquery/jquery#4989
Ref jquery/jquery#5139
=> jQuery.get:jQuery.post: Document issues with `data: null` with 3 params

entries/jQuery.find.xml
This change migrates most of https://github.com/jquery/sizzle/wiki to an API
page. Contrary to most other pages, each API didn't get its own XML `<entry>`
with a full signature to save time. This can be further improved in the future.
A Note section has been added, explaining the qSA to custom traversal fallback
mechanism of jQuery.
The browser support section has not been migrated as jQuery has different
browser support than Sizzle and it'd be irrelevant here.
Sizzle mentions have been replaced with `jQuery.find` or jQuery.
Fixes gh-1224
=> jQuery.find: Backport Sizzle wiki to an API page
